routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Auth::routes();
Route::get('register/verify/{token}', 'Auth\RegisterController@verifyUser');

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index');

Route::resource('rounds', 'RoundController', [
	'except' => ['edit', 'update']
]);
Route::resource('orders', 'OrderController', [
	'except' => ['index', 'show']
]);
Route::resource('items', 'ItemController', [
	'only' => ['store']
]);

app/Round.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Round extends Model
{
    protected $fillable = ['user_id','retrieve_self','active'];

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function orders()
    {
        return $this->hasMany('App\Order');
    }

    public function scopeActive($query)
    {
        return $query->where('active', true);
    }

    public function scopeLatest($query)
    {
        return $query->orderBy('created_at', 'desc');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'surname', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * Full name attribute combines first and surname.
     *
     * @return string
     */
    public function getFullNameAttribute()
    {
        return trim($this->name . " " . $this->surname);
    }

    /**
     * Get all rounds created by this user
     */
    public function rounds()
    {
        return $this->hasMany('App\Round');
    }
}

app/Http/Controllers/RoundController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Notification;

use Carbon\Carbon;

use App\Http\Requests;
use App\Round;
use App\Order;
use App\User;
use App\Notifications\NewCoffeeRound;
use App\Jobs\ProcessCoffeeRound;

class RoundController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('round.index', [
            'rounds' => Round::orderBy('created_at', 'desc')->get(),
            'num_active' => Round::active()->count(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('round.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if ($request->has('retrieve-type')) {
            $type = $request->input('retrieve-type');
            $user = Auth::user();

            // Create model
            $round = $user->rounds()->create([
                'active' => true,
                'retrieve_self' => $type == 'self'
            ]);

            return redirect()->to('rounds');
        }

        return redirect()->back()->withErrors([
            'retrieve-type' => 'Invalid retrieving choice.'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $round = Round::findOrFail($id);

        $order_placed = Order::inRound($id)->byUser(Auth::user()->id)->count() > 0;

        return view('round.show', [
            'round' => $round,
            'order_placed' => $order_placed,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $round = Round::findOrFail($id);
        $round->delete();
        return redirect()->to('rounds');
    }
}

resources/views/round/create.blade.php
@extends('layouts.mainpanel')

@section('title', 'Start new round')

@section('panel-body')
<form role="form" method="POST" action="{{ url('rounds') }}">
	{{ csrf_field() }}

	<p>Who should go and get everyone's coffee?</p>

	<div class="radio">
		<label>
			<input type="radio" id="retrieve-option1" name="retrieve-type" value="self" checked>
			Me
		</label>
	</div>
	<div class="radio">
		<label>
			<input type="radio" id="retrieve-option2" name="retrieve-type" value="random">
			Let the system decide
		</label>
	</div>

	<button type="submit" class="btn btn-success">Start</button>

</form>
@endsection

resources/views/round/index.blade.php
@extends('layouts.mainpanel')

@section('title', 'All coffee rounds')

@section('panel-body')
@if($num_active == 0)
<a href="{{ url('rounds/create') }}" class="btn btn-lg btn-success">Start new round</a>
<br><br>
@endif

@forelse($rounds as $round)
<p><a href="{{ url('rounds/'.$round->id) }}">Round by <strong>{{ is_null($round->user_id) ? 'system' : $round->user->full_name }}</strong> ({{ $round->active
	? $round->created_at->diffForHumans()
	: 'processed '.$round->updated_at->diffForHumans() }})</a></p>
@empty
<p>No round currently active.</p>
@endforelse
@endsection

resources/views/round/show.blade.php
@extends('layouts.mainpanel')

@section('title', 'Coffee round '. (is_null($round->user_id) ?
	'(automatic)' : 'by ' . $round->user->name))

@section('panel-body')
@if($message = Session::get('success'))
<div class="alert alert-success">
	<p>{{ $message }}</p>
</div>
@endif
@if($message = Session::get('warning'))
<div class="alert alert-warning">
	<p>{{ $message }}</p>
</div>
@endif

@unless($round->active)
<div class="alert alert-warning">
	<p>This round has already been processed.</p>
</div>
@endunless

<div class="clearfix">
	@if(!$order_placed && $round->active)
	<a href="{{ url('orders/create') }}" class="btn btn-success pull-left">Order up!</a>

	<form action="{{ url('orders') }}" method="POST" class="pull-left">
		{{ csrf_field() }}
		<input type="hidden" name="round_id" value="{{ $round->id }}">
		<input type="hidden" name="user_id" value="{{ Auth::user()->id }}">
		<input type="hidden" name="ignore" value="1">
		&nbsp;&nbsp;
		<button type="submit" class="btn btn-warning">No thanks</button>
		&nbsp;&nbsp;
	</form>
	@endif

	@if(Auth::user() == $round->user)
	<form action="{{ route('rounds.destroy', $round->id) }}" method="POST" class="pull-left">
		{{ method_field("DELETE") }}
		{{ csrf_field() }}
		<div class="form-group">
			<button class="btn btn-danger" type="submit" onclick="confirm('Are you sure?')">Delete round</button>
		</div>
	</form>
	@endif
</div>

<p>Started at: {{ $round->created_at->format('M j, H:i') }} ({{ $round->created_at->diffForHumans() }})</p>
<p>Retriever: {{ $round->retrieve_self ? $round->user->name : '(random selection)' }}</p>

<h4>Orders</h4>
<ul>
	@forelse($round->orders as $o)
	@if($o->ignore)
	<li><i>{{ $o->user->name }} ignored this round</i></li>
	@else
	<li><b>{{ $o->user->name }}</b> ordered <b>{{ $o->item->description }}</b></li>
	@endif
	@empty
	<li><i>(None)</i></li>
	@endforelse
</ul>
@endsection